#!/usr/bin/env python3
"""
Transform FF7_Savemap.md to standardized format.
Created: 2025-12-02 00:35 JST
Session-ID: e122674d-efd3-47e8-a58f-3dcc9c8763f5

This script transforms the FF7_Savemap.md document to meet documentation
standardization requirements including:
- YAML frontmatter with LLM metadata
- HTML comment metadata block
- Fixed heading hierarchy
- Converted wiki-style links
"""

import re
from pathlib import Path

# Paths
SOURCE = Path("/Volumes/DevSSD/01_Development/Projects/experiments/ff70G-japanese-mod/docs/reference/game_engine/markdown/merged_with_pdf_content/FF7_Savemap.md")
DEST = Path("/Volumes/DevSSD/01_Development/Projects/experiments/ff70G-japanese-mod/docs/reference/game_engine/final/FF7_Savemap.md")

# YAML Frontmatter
YAML_FRONTMATTER = '''---
title: "FF7/Savemap"
module: "Reference"
created: "2025-11-28 15:50 JST"
modified: "2025-12-02 00:35 JST"
session_id: "e122674d-efd3-47e8-a58f-3dcc9c8763f5"
author: "Generated by Claude Code Documentation Standardization Agent"
status: "Complete"

# LLM-specific metadata (CRITICAL for routing)
llm_summary: "Comprehensive specification of FF7 save file memory layout including character records, item/materia storage, chocobo data, field script memory banks, and game progress flags. LLMs should read this when parsing save files, debugging game state issues, or implementing save file editors."
llm_tags: ["save-file", "memory-map", "character-data", "game-state", "field-script", "chocobo-breeding"]
llm_primary_topics: ["Save file structure", "Character record format", "Field script memory banks", "Item and materia storage", "Chocobo records", "Game progress flags"]
llm_related_docs: ["FF7_Kernel.md", "FF7_Menu_Module.md", "FF7_Field_Module.md", "FF7_Item_Materia_Reference.md"]

# Backlinks (leave empty - populated in pass 2)
referenced_by: []
---

'''

# HTML Comment Metadata Block
HTML_METADATA = '''<!--
STANDARDIZATION METADATA
Original: FF7_Savemap.md
Source: merged_with_pdf_content/FF7_Savemap.md
Standardized: 2025-12-02 00:35 JST
Session-ID: e122674d-efd3-47e8-a58f-3dcc9c8763f5
Agent: FF7 Documentation Standardization Agent v1.0

Previous Merge Metadata:
=== MERGE METADATA ===
File: FF7_Savemap.md
Merged: 2025-11-28 15:50 JST (Friday)
Source: /docs/reference/game_engine/markdown/FF7_Savemap.md (ORIGINAL - NO EXTRACTION FROM 03_KERNEL.md)
Major Section: 03_KERNEL.md (lines 1-1641)
Analysis Report: /docs/reference/game_engine/comparisons/FF7_Savemap_vs_03_KERNEL_analysis.md

MERGE STATUS: Complete
Content Extraction from Major Section: NO EXTRACTION PERFORMED
Reason: Individual file is significantly more detailed (3,861 lines vs 1,641 lines in major section)
         and is the authoritative source for savemap documentation.

The 03_KERNEL.md major section includes only a brief reference to savemap (lines 190-192)
that states: "This is all the initial values and structure for most of the Savemap, excluding
the header data and the tail of the last bank."

The FF7_Savemap.md individual file contains extensive, comprehensive documentation with:
- Complete memory bank structures (Banks 1/2, 3/4, B/C, D/E, 7/F)
- Character record details
- Chocobo record data
- Item and materia list structures
- Detailed field-by-field breakdown with offsets and descriptions

All original content from FF7_Savemap.md has been preserved verbatim.
===  END MERGE METADATA ===

Standardization Changes Applied:
- Added YAML frontmatter with LLM routing metadata
- Added this HTML comment metadata block preserving original merge metadata
- Fixed heading hierarchy: H3 "The Savemap" promoted to H2 (was skipping H2 level)
- Converted 1 markdown wiki-style link to standard format
- Preserved 80+ HTML wikilink references within tables (complex HTML table structure)
- All HTML tables preserved as-is due to complex styling requirements

LLM CONTEXT BLOCK (Read this first for routing decisions):
This document is the authoritative reference for FF7 save file structure, containing complete
memory offset specifications from 0x0000 to 0x10A3. It covers: save preview data, 9 character
records (132 bytes each), party inventory (320 item slots), materia storage (200 slots),
five field script memory banks with game progress flags, chocobo breeding data, minigame
scores, and world map state. Essential for save file editing tools, game state debugging,
and understanding how FF7 persists game progress.
-->

'''

def transform_content(content: str) -> str:
    """Transform the document content."""

    # Remove old HTML comment metadata block
    content = re.sub(r'^<!--[\s\S]*?-->\s*', '', content, count=1)

    # Remove old Table of Contents (lines 31-43)
    # Pattern: starts with "- [FF7/Savemap]" and contains the TOC
    toc_pattern = r'^- \[FF7/Savemap\].*?\n(?:  - \[.*?\n)*\n*'
    content = re.sub(toc_pattern, '', content, flags=re.MULTILINE)

    # Fix heading hierarchy: "### The Savemap" should be "## The Savemap"
    content = re.sub(r'^### The Savemap', '## The Savemap', content, flags=re.MULTILINE)

    # Convert markdown wiki-style link: [text](url "title"){.wikilink}
    # Pattern at line 3883: [LBS 0](Bit_numbering "LBS 0"){.wikilink}
    content = re.sub(
        r'\[([^\]]+)\]\(([^"]+)\s+"[^"]*"\)\{\.wikilink\}',
        r'[\1](\2)',
        content
    )

    return content

def main():
    print("Reading source file...")
    content = SOURCE.read_text(encoding='utf-8')
    original_lines = len(content.splitlines())

    print("Transforming content...")
    content = transform_content(content)

    # Assemble final document
    final_content = YAML_FRONTMATTER + HTML_METADATA + content

    # Ensure destination directory exists
    DEST.parent.mkdir(parents=True, exist_ok=True)

    print(f"Writing to {DEST}...")
    DEST.write_text(final_content, encoding='utf-8')

    final_lines = len(final_content.splitlines())
    print(f"Done! Original: {original_lines} lines, Final: {final_lines} lines")

    # Count statistics
    wiki_links_in_html = len(re.findall(r'class="wikilink"', final_content))
    tables_count = len(re.findall(r'<table', final_content, re.IGNORECASE))

    print(f"Statistics:")
    print(f"  - Wiki-style links in HTML tables: {wiki_links_in_html}")
    print(f"  - HTML tables: {tables_count}")

if __name__ == "__main__":
    main()
