[package]
name = "bg-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "bg-updater"
path = "src/main.rs"

[dependencies]
bg-core = { workspace = true }
bg-formats = { workspace = true }
clap.workspace = true
anyhow.workspace = true
